---
- hosts: "{{ hostname }}"
  tasks:
    - name: Start the Online Banking node service
      service: 
        name: onlinebanking
        state: started

    - debug:
        msg: Access Online Banking using http://sample.ba.x.y.example.com:3000
