---
- hosts: all
  tasks:
    - name: Start the Online Banking node service
      service: 
        name: onlinebanking
        state: stopped

    - debug: var=finalout.stdout_lines

    - debug:
        msg: Access Online Banking using http://sample.ba.x.y.example.com:3000
